### ISSUE TITLE
[Feature Request] Place address components

### ISSUE THREAD

**Issue by zanesc** [muhaym/CrossPlacePicker#10]
Can you make the place address components accessible?

https://developers.google.com/places/web-service/details

**Comment by muhaym** [comment]
`/// <summary>
        /// Returns a human readable address for this Place. May return null if the address is unknown. 
        /// </summary>
public string Address { get; private set; }`

Result already have address.

**Comment by muhaym** [comment]
``

**Comment by zanesc** [comment]
I know that the results have an address. That’s not what I asked about.

The address components break down the address and separates the components so that you can know what the city is, what the country is, and so on. With the addresss string currently returned there is no way of determining which part of the address is the city.
