### ISSUE TITLE
Map never loads in

### ISSUE THREAD

**Issue by saphraxaeris** [muhaym/CrossPlacePicker#4]
When displaying the picker the actual map will not load in. The places and coordinates work fine.

Example:
![20171010_020417000_ios](https://user-images.githubusercontent.com/7504362/31367478-9465cd66-ad45-11e7-9ff1-b2f38779992f.png)

**Comment by muhaym** [comment]
Enable Place Service from Google Api Console.

**Comment by saphraxaeris** [comment]
Thank you. It was enabled, but disabling and re-enabling fixed the problem. I'm writing this as a tip for people with the same problem.

**Comment by ali-h2010** [comment]
Hi Everyone, 
I tried all solutions above and still the map is not loading in iOS.
Can someone please help with this issue?

**Comment by ali-h2010** [comment]
I deleted the API Key and strangely the app was still working but the map doesn't load even if the key is valid and correct

**Comment by ali-h2010** [comment]
I noticed that there are errors in the traffic request but there is no indication of type or any details
<img width="1617" alt="screen shot 2018-11-12 at 10 37 47 pm" src="https://user-images.githubusercontent.com/12033261/48370932-99547a00-e6cb-11e8-8ec2-9864ec0c6a8e.png">

**Comment by ali-h2010** [comment]
@muhaym 
Is this related to the issue 
https://stackoverflow.com/questions/15799411/google-maps-sdk-for-ios-doesnt-display-map-content

**Comment by ali-h2010** [comment]
It worked now after enabling all map related API services
