### ISSUE TITLE
Locale is not affecting PlacePicker language in Anroid

### ISSUE THREAD

**Issue by afzalali15** [muhaym/CrossPlacePicker#5]
It works perfectly for iOS with locale applied as "ar" but doesn't effect in Android.

**Comment by muhaym** [comment]
Could you please elaborate the issue, which part of the UI with screenshots.

**Comment by afzalali15** [comment]
Hi Muhaym, 

I have cross platform application for Android and iOS. I have applied locale with Arabic language to both platforms.

Problem is, When I open PlacePicker on Android it doesn't take Arabic language and entire screen comes with English text. But at same time in iOS application PlacePicker shows with Arabic content. 

I can confirm that locale has applied in both Android and iOS as I can see other controls RTL behaviour.
<img width="784" alt="locale_issue_android" src="https://user-images.githubusercontent.com/15074647/31582687-4bc27a26-b193-11e7-86b3-2309591eb7a6.png">

**Comment by muhaym** [comment]
It's not handled manually, if you can implement it in native, please do provide link, I will check

**Comment by afzalali15** [comment]
Yes, you are right! Even in Native Android implementation, Place picker doesn't support locale.  
I realized that this issue is with PlacePicker control. 

Interestingly, **Google** place picker not working properly in **Android** but working fine in **iOS**. 🤣
