### ISSUE TITLE
Could not load assembly 'Plugin.CrossPlacePicker.Abstractions

### ISSUE THREAD

**Issue by rtahir** [muhaym/CrossPlacePicker#7]
Hello ..
I'm using the plugin at my project (portable Xamarin forms) , getting the following error 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.CrossPlacePicker.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Plugin.CrossPlacePicker.Abstractions.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/data/lanes/5749/d8c6e504/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 229
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	SpotApp.Android			

![err1](https://user-images.githubusercontent.com/13960606/34816485-ea47c7da-f669-11e7-90ea-de69267636b5.jpg)

The code 
======

try
                {
                    var result = await CrossPlacePicker.Current.Display();
                    if (result != null)
                    {
                        LocationModel l = new LocationModel();
                        l.locationType = result.Name;
                        l.dsc = spotTitle;
                        l.lat = result.Coordinates.Latitude+"";
                        l.lng = result.Coordinates.Longitude + "";
                        Locations.Add(l);
                    }
                }
                catch (Exception ex)
                {
                    await _dialogService.DisplayAlertAsync("Error", ex.ToString(), "Oops");
                }

AndroidManifest
===========

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.SpotApp" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="23" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
	<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
	<application android:label="SpotApp.Android">
		<meta-data 
      android:name="com.google.android.geo.API_KEY" 
      android:value="MY-API-KEY" />
		<provider 
      android:name="android.support.v4.content.FileProvider" 
      android:authorities="SpotApp.fileprovider" 
      android:exported="false" 
      android:grantUriPermissions="true">
			<meta-data 
        android:name="android.support.FILE_PROVIDER_PATHS" 
        android:resource="@xml/file_paths"></meta-data>
		</provider>
	</application>
</manifest>

**Comment by muhaym** [comment]
I guess the issue is currently library doesn't support .NET Standard, will be updating soon to provide support to Latest Google Place Picker on iOS and .NET Standard Support

**Comment by muhaym** [comment]
Upgraded to .NET Standard. Please try and report
