### ISSUE TITLE
Xamrin Forms Android: RuntimeException

### ISSUE THREAD

**Issue by Jose04Fajardo** [muhaym/CrossPlacePicker#8]
Hi, i try to implement this Plugin in my project, and with IO's i don't have problems at all, but with Android appear the following Exception:

Java.Lang.RuntimeException:
Attempt to invoke virtual method 
'java.lang.String android.content.Context.getPackageName()'
on a null object reference...

this where i implement the code in xamarin forms:
```CSHARP
 async void Mapa()
        {
            try
            {
               var result = await CrossPlacePicker.Current.Display();
                if (result != null)
                    {
                        await DisplayAlert(result.Name, "Latitude: " + result.Coordinates.Latitude + "\nLongitude: " + result.Coordinates.Longitude + "\nDireccion: " + result.Address, "OK");
                        adress = result.Address;
                    }
            }
            catch (Exception ex)
            {
                await DisplayAlert("Error", ex.ToString(), "Oops");
            }
        }
```
could you help me?

**Comment by muhaym** [comment]
Hi, Could you please confirm whether
https://github.com/muhaym/CrossPlacePicker#android
configurations are done properly?

**Comment by Jose04Fajardo** [comment]
i used to use the following:
android:name="com.google.android.maps.v2.API_KEY",
 but i changed by:
 android:name="com.google.android.geo.API_KEY"
as you explain in your example.

and i have the same permission, even COARSE_LOCATION

i used two api keys, one for android and another one for iOS.

**Comment by muhaym** [comment]
Can you share your AndroidManifest.xml file.

**Comment by Jose04Fajardo** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.1.3" package="klin.Android" android:installLocation="preferExternal" android:versionCode="20">
	<uses-sdk android:minSdkVersion="15" />
	<application android:label="Klin Cliente" android:icon="@drawable/icon">
		<meta-data android:name="com.google.android.geo.API_KEY" android:value="(HERE GO MY API KEY)" />
		<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
		<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />
	</application>
	<uses-permission android:name="com.google.android.providers.gsf.permission.READ_GSERVICES" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_LOCATION_EXTRA_COMMANDS" />
	<uses-permission android:name="android.permission.ACCESS_MOCK_LOCATION" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.ACCESS_SURFACE_FLINGER" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.INTERNET" />
</manifest>
```

**Comment by muhaym** [comment]
You don't have any exception when not using this library?

**Comment by Jose04Fajardo** [comment]
the exception only appear when i click in the button to show the map, even in the example that you made

**Comment by muhaym** [comment]
If you can provide a repro project, it would help, because it's working in live projects without issue

**Comment by Jose04Fajardo** [comment]
repro project? 
did you need where the code call the function?

**Comment by muhaym** [comment]
@Jose04Fajardo  Sorry for late reply, had a very busy week. Repro where I can get the same exception, if it's your private project you don't wish to share, share it privately through mampary at hotmail com

**Comment by Abrancill0** [comment]
nice, thanks for the explanation, well actually i saw my error, i forgot to put the MainApplication.cs file in my .Droid app, now it shows the map,
thanks anyway for your time and attention
